HOST="${HOST:-localhost}"
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-dbname}"
DB_USER="${DB_USER:-user}"
DB_PASSWORD="${DB_PASSWORD:-pasword}"
JWT_SECRET="${JWT_SECRET:-secret}"
JWT_TTL="${JWT_TTL:-3600}"
JWT_REFRESH_TTL="${JWT_REFRESH_TTL:-2592000}"
export HOST DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD JWT_SECRET JWT_TTL JWT_REFRESH_TTL

exec ./bin/app
