services:
  app:
    container_name: todo-manager-app
    image: docker.io/golang:1.25.1-alpine3.22
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - ./.env
    command: sh -c '/app/bin/app'
    networks:
      todo_manager_network:
        aliases:
          - app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${APP_CPUS}
          memory: ${APP_MEMORY}
    depends_on:
      - db
  db:
    container_name: todo-manager-db
    image: docker.io/postgres:15.14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      todo_manager_network:
        aliases:
          - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${DB_CPUS}
          memory: ${DB_MEMORY}
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 30s
networks:
  todo_manager_network:
    driver: bridge
