services:
  app:
    container_name: todo-manager_app
    image: docker.io/golang:1.24.2-bookworm
    volumes:
      - ./:/app
      # - ./go_packages:/go/pkg/mod
    working_dir: /app
    env_file:
      - ./.env
    command: sh -c '/app/bin/app'
    # command: sh -c 'cd /app && go mod tidy && go mod vendor && go build -v -o ./bin/app ./cmd && ./bin/app'
    networks:
      podman_network:
        aliases:
          - todo-manager
    restart: unless-stopped
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: ${TODO_MANAGER_APP_CPUS}
          memory: ${TODO_MANAGER_APP_MEMORY}
    # depends_on:
    #   - db
  db:
    container_name: todo-manager_db
    image: docker.io/postgres:15.10-bookworm
    environment:
      POSTGRES_DB: ${TODO_MANAGER_DB_NAME}
      POSTGRES_USER: ${TODO_MANAGER_DB_USER}
      POSTGRES_PASSWORD: ${TODO_MANAGER_DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      podman_network:
        aliases:
          - todo-manager-db
    ports:
      - 5432:5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${TODO_MANAGER_DB_CPUS}
          memory: ${TODO_MANAGER_DB_MEMORY}
networks:
  podman_network:
    # external: true
    driver: bridge
